/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const JobsSalaryLevelsLazyImport = createFileRoute('/jobs/salary-levels')()
const JobsEducationLevelsLazyImport = createFileRoute(
  '/jobs/education-levels',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const JobsSalaryLevelsLazyRoute = JobsSalaryLevelsLazyImport.update({
  path: '/jobs/salary-levels',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/jobs/salary-levels.lazy').then((d) => d.Route),
)

const JobsEducationLevelsLazyRoute = JobsEducationLevelsLazyImport.update({
  path: '/jobs/education-levels',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/jobs/education-levels.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/jobs/education-levels': {
      preLoaderRoute: typeof JobsEducationLevelsLazyImport
      parentRoute: typeof rootRoute
    }
    '/jobs/salary-levels': {
      preLoaderRoute: typeof JobsSalaryLevelsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  JobsEducationLevelsLazyRoute,
  JobsSalaryLevelsLazyRoute,
])

/* prettier-ignore-end */
